on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - run: npm ci

      - name: 🔨 Build Project
        run: |
          npm install
          npm ci
      # - run: printf $DEV_ENV_FILE >> src/.env
      # - run: printf $DEV_ENV_FILE
      # - run: cat src/.env

      - name: Create .secrets file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_TEST_API_KEY: ${{ secrets.FTP_SERVER }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          file_name: .secrets.yaml # optional (default: .env)
          fail_on_empty: false # optional (default: false)

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            wsgi_dev.py
            README.md
